<?php
return array (
  0 => 'OscMAX',
  1 => 'H:i',
  2 => '.',
  3 => ',',
  4 => '+',
  5 => '-',
  6 => 'NA',
  7 => 'MIME:',
  8 => 'IM',
  9 => 'API',
  10 => 'SMTP',
  11 => 'SKU',
  12 => 'ltr',
  13 => 'm/d/Y',
  14 => 'h:i:s A',
  15 => '(CVV2 ?)',
  16 => 'Fedex',
  17 => 'https://avatax.avalara.net',
  18 => 'https://development.avalara.net',
  19 => 'CardConnect',
  20 => '2Checkout',
  21 => 'Twilio',
  22 => '&nbsp;',
  23 => 'ACSS',
  24 => 'Affirm',
  25 => 'EPS',
  26 => 'FPX',
  27 => 'UPS',
);
