<?php
return array (
  0 => false,
  1 => 'ZenCart 1.3.9h',
  2 => 'H:i',
  3 => '+',
  4 => '-',
  5 => 'MIME:',
  6 => 'IM',
  7 => 'SMTP',
  8 => '(CVV2 ?)',
  9 => 'Fedex',
  10 => 'https://avatax.avalara.net',
  11 => 'https://development.avalara.net',
  12 => '2Checkout',
  13 => 'Sameday®',
  14 => '&nbsp;',
  15 => 'ACSS',
  16 => 'Affirm',
  17 => 'Swish',
  18 => 'EPS',
  19 => 'FPX',
  20 => 'iDEAL',
  21 => 'UPS Saver',
  22 => '{start} - {end} of {total}',
);
