<?php
return array (
  0 => 'ZenCart 1.3.9h',
  1 => 'm/d/Y',
  2 => 'h:i:s A',
  3 => 'H:i',
  4 => '.',
  5 => ',',
  6 => '+',
  7 => '-',
  8 => '(Default)',
  9 => 'IM',
  10 => 'NA',
  11 => 'MIME:',
  12 => 'SKU',
  13 => 'IM:',
  14 => 'HTML',
  15 => 'en',
  16 => 'ltr',
  17 => '{start} - {end} of {total}',
  18 => 'Fedex',
  19 => 'https://avatax.avalara.net',
  20 => 'https://development.avalara.net',
  21 => '(CVV2 ?)',
  22 => '2Checkout',
  23 => 'Parcelforce 48',
  24 => 'Sameday® (for GB only)',
  25 => 'TextMarketer',
  26 => '&nbsp;',
  27 => 'Bancontact',
  28 => 'EPS',
  29 => 'UPS',
);
