<?php
return array (
  1 => 'CardConnect',
  2 => 'CardKnox',
  3 => '2Checkout',
  4 => 'LIQPAY',
  5 => 'Parcelforce 48',
  6 => 'Mail 48®',
  7 => 'Sameday®',
  8 => 'API AccountSID',
  9 => 'ACSS',
  10 => 'Afterpay/Clearpay',
  11 => 'Alipay',
  12 => 'Bancontact',
  13 => 'Revolut Pay',
  14 => 'EPS',
  15 => 'FPX',
  16 => 'giropay',
  17 => 'Grabpay',
  18 => 'iDEAL',
  19 => 'OXXO',
  20 => 'Przelewy24',
  21 => 'PromptPay',
  22 => 'WeChat Pay',
  23 => 'TWINT',
  24 => 'UPS',
  25 => 'https://avatax.avalara.net',
  26 => 'https://development.avalara.net',
);
