name: "tagged-release"

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project
        run: |
          cd ..
          mkdir assets
          php ./abantecart-languages/.github/workflows/asset_builder.php ${{ github.ref_name }} 1.4
          cd assets && for dir in */ ; do tar -czvf "${dir%/}.tar.gz" "$dir"; done
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          tag: ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Directory listing
        run: |
          cd ..
          ls -la
      - name: Upload Release Asset tar.gz
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          files: |            
            ../assets/*.tar.gz
