name: "tagged-release"

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project
        run: |
          cd ..
          tar -czvf default_ukrainian.tar.gz  abantecart-languages/default_ukrainian
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          tag: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Directory listing
        run: |
          cd ..
          ls -la
      - name: Upload Release Asset targz
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          files: |
            ../default_ukrainian.zip
            ../default_ukrainian.tar.gz

